---

# Gitlab-ce
gitlab_edition: "gitlab-ce"
#gitlab_version: '12.4.1-ce.0'

# codedeploy
codedeploy:
  aws_region: "ap-northeast-2"

# java
# amazon/fedora/redhat : 1.8.0, 11, 13
# debian/ubuntu : 8, 11, 13
# freebsd : 6, 8, 11, 13
java:
  redhat_version: 1.8.0
  debian_version: 8

# Gradle
# available version (6.2.2, 4.8.1)
gradle:
  version: '4.8.1'
  dir: "/opt"

# Maven
# available version (3.6.3, 3.6.2, 3.6.1, 3.6.0, 3.5.4, 3.5.3, 3.5.2, 3.5.0, 3.3.9, 3.2.5, 3.1.1)
maven:
  version: '3.6.3'
  dir: "/opt"

# Nexus
nexus_admin_password: changeme
nexus_default_port: 8081
nexus_min_heap_size: 800M
nexus_max_heap_size: 1000M
nexus_max_direct_memory: 1000M

# jenkins
jenkins_http_port: 8088

# Packer
packer:
  version: "1.3.1"
  dir: "/opt/packer"

# node version
node:
  version: "11.x"

# nginx
nginx:
  version: "nginx"
  aws_version: "nginx1.12"

# terraform
terraform:
  version: "0.12.23"
  dir: "/opt"
