---
- name: apt update
  shell: apt update

- name: Update all Ubuntu packages
  apt:
    update_cache: yes

- name: Ensure 'man' directory exists.
  file:
    path: /usr/share/man/man1
    state: directory
    recurse: true
  when:
    - ansible_distribution == 'Ubuntu'
    - ansible_distribution_version == '18.04'

- name: Ensure nginx is installed.
  apt:
    name: "{{ nginx.version }}"
    state: present

- name: restart nginx
  service: name=nginx state=started