---
#- name: apt update
#  shell: apt update

#- name: Update all Ubuntu packages
#  apt:
#  update_cache: yes

- name: Update apt-get repo and cache
  apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

- name: "Install Packages | package manager"
  package:
    state: latest
    name: "{{ item }}"
    update_cache: yes
  with_items: "{{ packages }}"
